### ISSUE TITLE
Tooltips causing GUI to misbehave

### ISSUE THREAD

**Issue by spaceymonk** [ozkaberktug/flower#2]
When mouse is on the menubar items after tooltip appears, draw panel moves left and on the right
it creates a gap

**Comment by ozkaberktug** [comment]
Possibly caused by UI Manager (using different paint method for that component -ie DrawPanel). Blocked component's paint method does not use AffineTransformation.

**Comment by spaceymonk** [comment]
**Summary**

_Problem:_ When JPanel obscured by other components, some kind of affine transformation applying to it and causing distortion.

_Cause:_ Swing applies a transform to it's graphics object. Therefore whenever you use `graphics.setTransform(yourVeryOwnTransform)` will erase the previous transform and sometimes this will cause distortion.

_Solution:_ Instead of applying transform directly as `graphics.setTransform(...)`, do it step by step like:

```
    AffineTransform af = graphics.getTransform();
    af.translate(yours.getTranslateX(), yours.getTranslateY());  
    af.scale(..);
    ...   // if you use other transforms like rotation, shearing etc. add them as well
```
